[package]
name = "tysql"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
itertools = "0.14.0"
pg_query = "6.0.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-postgres = { version = "0.7.13", features = ["array-impls"] }
