use std::sync::{Arc, OnceLock, Weak};

use testcontainers_modules::{
    postgres::Postgres,
    testcontainers::{ContainerAsync, ImageExt},
};
use tokio::{io::AsyncWriteExt, sync::Mutex};

use crate::translate_file;

pub(crate) async fn db_transaction() -> (
    Arc<ContainerAsync<Postgres>>,
    tokio_postgres::Transaction<'static>,
) {
    use testcontainers_modules::testcontainers::runners::AsyncRunner;
    // https://github.com/testcontainers/testcontainers-rs/issues/707#issuecomment-2248314261
    static C: OnceLock<Mutex<Weak<ContainerAsync<Postgres>>>> = OnceLock::new();

    let mut guard = C.get_or_init(|| Mutex::new(Weak::new())).lock().await;
    let c = if let Some(c) = guard.upgrade() {
        c
    } else {
        let c = testcontainers_modules::postgres::Postgres::default()
            .with_tag("16-alpine")
            .with_container_name("pg-sqlc-test")
            .start()
            .await
            .unwrap();
        let c = Arc::new(c);
        *guard = Arc::downgrade(&c);

        c
    };
    let host_port = c.get_host_port_ipv4(5432).await.unwrap();
    let url = format!("postgres://postgres:postgres@localhost:{host_port}/postgres");

    let (client, connection) = tokio_postgres::connect(&url, tokio_postgres::NoTls)
        .await
        .unwrap();

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("connection error: {}", e);
        }
    });
    // TODO: client pool
    let client = Box::leak(Box::new(client));
    let t = client.transaction().await.unwrap();

    (c, t)
}

const SEED_TABLES: &str = "
CREATE TABLE films(
    film_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    language_id integer NOT NULL,
    original_language_id integer
);

CREATE TABLE languages (
    language_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL
);
";

async fn e2e(ps: &str) -> String {
    let (_c, t) = db_transaction().await;
    t.batch_execute(SEED_TABLES).await.unwrap();

    let mut sql = std::io::Cursor::new(ps);
    let mut rs = std::io::Cursor::new(Vec::new());

    translate_file(&t, &mut sql, &mut rs).await.unwrap();
    String::from_utf8(rs.into_inner()).unwrap()
}

macro_rules! t {
    ($fname:ident, $arg:literal) => {
        #[tokio::test]
        async fn $fname() {
            let rs = crate::test::e2e($arg).await;
            insta::assert_snapshot!(rs);
        }
    };
}

mod select {
    t!(
        without_input,
        "PREPARE list_films AS SELECT film_id, title FROM films;"
    );

    t!(
        with_input,
        "PREPARE find_film AS SELECT film_id, title FROM films where film_id = $1;"
    );

    t!(
        with_input_right,
        "PREPARE find_film AS SELECT film_id, title FROM films where $1 = film_id;"
    );

    t!(
        with_multiple_inputs,
        "PREPARE find_film AS SELECT film_id, title FROM films WHERE film_id > $1 AND title LIKE $2;"
    );
}

mod insert {
    t!(
        basic,
        "PREPARE create_film AS INSERT INTO films(title) VALUES ($1);"
    );

    t!(
        with_returning,
        "PREPARE create_film AS INSERT INTO films(title) VALUES ($1) RETURNING film_id;"
    );
}

mod update {
    t!(
        basic,
        "PREPARE update_user AS UPDATE films SET title = $2 WHERE film_id = $1;"
    );

    t!(
        with_return,
        "PREPARE update_user AS UPDATE films SET title = $2 WHERE film_id = $1 RETURNING film_id, title;"
    );
}

mod delete {

    t!(
        basic,
        "PREPARE delete_user AS DELETE FROM films WHERE film_id = $1"
    );

    t!(
        with_return,
        "PREPARE delete_user AS DELETE FROM films WHERE film_id = $1 returning film_id, title"
    );
}

t!(
    multiple_prepare,
    "PREPARE list_films AS SELECT film_id, title FROM films;
     PREPARE find_user AS SELECT film_id, title FROM films where film_id = $1;"
);

#[tokio::test]
async fn fill_example() {
    let (_c, t) = db_transaction().await;
    t.batch_execute(SEED_TABLES).await.unwrap();

    let mut sql = std::io::Cursor::new(include_str!("../examples/films.sql"));
    let mut rs = tokio::fs::File::create("./examples/films.rs")
        .await
        .unwrap();
    translate_file(&t, &mut sql, &mut rs).await.unwrap();
    rs.write_all(
        b"\n// The main is not autogenerated, but is needed to example folder to compile\n",
    )
    .await
    .unwrap();
    rs.write_all(
        stringify! {
            fn main() {}
        }
        .as_bytes(),
    )
    .await
    .unwrap();
}
